1void HGC_EFF(){                                                                                                                                                                                                                       
 2  gStyle->SetOptStat(0);                                                                                                                                                                                                              
 3  TFile *f = (TFile*)gROOT->GetListOfFiles()->FindObject("coin_replay_production_3435_good_-1.root");                                                                                                                                 
 4  if (!f) {                                                                                                                                                                                                                           
 5    f = new TFile("coin_replay_production_3435_good_-1.root"); //3584 -2.53w                                                                                                                                                          
 6  }                                                                                                                                                                                                                                   
 7  TH1F *hTotal = new TH1F ("hTotal","",20,-10,20);                                                                                                                                                                                    
 8  TH1F *hPass = new TH1F("hpass","",20,-10,20);                                                                                                                                                                                       
 9  TH2F *h = new TH2F("h","Efficiency vs Delta 3435 P = +3.37",20,-10,20,100,0,1);                                                                                                                                                     
10  //  TH2F *h1[k] = new TH2F("h1[k]","Efficiency vs Aerogel Cut 3435 P = +3.37",20,0,3.5,100,0,1);                                                                                                                                    
11                                                                                                                                                                                                                                      
12                                                                                                                                                                                                                                      
13  Double_t pgtrbeta,pgtrdp,paeronpesum,pcaleprtracknorm,pcaletottracknorm,pngcernpesum,phgcernpesum,pdcxfp,pdcxpfp,pcaletracknorm,pcaletotnorm;//,ctime;                                                                              
14                                                                                                                                                                                                                                      
15  TTree *tree = (TTree*) f->Get("T");                                                                                                                                                                                                 
16                                                                                                                                                                                                                                      
17  //  tree->SetBranchAddress("CTime.ePiCoinTime_ROC2" ,&ctime);                                                                                                                                                                       
18  tree->SetBranchAddress("P.gtr.beta" ,&pgtrbeta);                                                                                                                                                                                    
19  tree->SetBranchAddress("P.gtr.dp" ,&pgtrdp);                                                                                                                                                                                        
20  tree->SetBranchAddress("P.cal.eprtracknorm" ,&pcaleprtracknorm);                                                                                                                                                                    
21  tree->SetBranchAddress("P.cal.etottracknorm" ,&pcaletottracknorm);                                                                                                                                                                  
22  tree->SetBranchAddress("P.ngcer.npeSum" ,&pngcernpesum);                                                                                                                                                                            
23  tree->SetBranchAddress("P.hgcer.npeSum" ,&phgcernpesum);                                                                                                                                                                            
24  tree->SetBranchAddress("P.aero.npeSum" ,&paeronpesum);                                                                                                                                                                              
25  tree->SetBranchAddress("P.dc.x_fp" ,&pdcxfp);                                                                                                                                                                                       
26  tree->SetBranchAddress("P.dc.xp_fp" ,&pdcxpfp);                                                                                                                                                                                     
27  tree->SetBranchAddress("P.cal.etracknorm" ,&pcaletracknorm);                                                                                                                                                                        
28  tree->SetBranchAddress("P.cal.etotnorm" ,&pcaletotnorm);                                                                                                                                                                            
29                                                                                                                                                                                                                                      
30  // Float_t x1[6] = {0.0,0.1,0.2,0.3,0.4,0.5};//,0.6,0.7,0.8,0.9,1.0,1.1,1.2,1.3,1.4,1.5,1.6,1.7,1.8,1.9,2.0,2.1,2.2,2.3,2.4,2.5,2.6,2.7,2.8,2.9,3.0};                                                                               
31  // for ( k =0,k<5; k++){                                                                                                                                                                                                            
32                                                                                                                                                                                                                                      
33  Long64_t nentries =tree->GetEntries();                                                                                                                                                                                              
34  for (Long64_t i=0; i<nentries; i++)                                                                                                                                                                                                 
35    {                                                                                                                                                                                                                                 
36      tree->GetEntry(i);                                                                                                                                                                                                              
37      if (pgtrbeta>0.8&&pgtrbeta<1.3&&pgtrdp<20&&pgtrdp>-10&&paeronpesum>3.0)                                                                                                                                                         
38        {                                                                                                                                                                                                                             
39          hTotal->Fill(pgtrdp);  //  hTotal->Fill(pdcxfp);                                                                                                                                                                            
40          if (phgcernpesum>0.5)                                                                                                                                                                                                       
41            {                                                                                                                                                                                                                         
42              hPass->Fill(pgtrdp); // hPass->Fill(pdcxfp);                                                                                                                                                                            
43            }                                                                                                                                                                                                                         
44        }                                                                                                                                                                                                                             
45    }                                                                                                                                                                                                                                 
46                                                                                                                                                                                                                                      
47  TEfficiency *pEff = new TEfficiency();                                                                                                                                                                                              
48  pEff = new TEfficiency(*hPass, *hTotal);                                                                                                                                                                                            
49  cout << "======================================================================" <<endl;                                                                                                                                            
50  cout<<"hTotal nEntries ="<<hTotal->GetEntries()<<endl;                                                                                                                                                                              
51  cout<<"hPass nEntries ="<<hPass->GetEntries()<<endl;                                                                                                                                                                                
52  Double_t Should = hTotal->GetEntries();                                                                                                                                                                                             
53  Double_t Did = hPass->GetEntries();                                                                                                                                                                                                 
54  if(Did == 0)                                                                                                                                                                                                                        
55    cout << "SHMS hgcer efficiency: "<< 0 <<" %"<<endl;                                                                                                                                                                               
56  else                                                                                                                                                                                                                                
57    cout << "SHMS hgcer efficiency: "<< Did*100/Should <<" %"<<endl;                                                                                                                                                                  
58  cout<<"======================================================================" <<endl;                                                                                                                                              
59                                                                                                                                                                                                                                      
60                                                                                                                                                                                                                                      
61  TCanvas *c1 = new TCanvas("c1", "", 500,500);                                                                                                                                                                                       
62  // c1->Divide(2,1);                                                                                                                                                                                                                 
63  c1->cd();                                                                                                                                                                                                                           
64  c1->SetGrid();                                                                                                                                                                                                                      
65  h->GetXaxis()->CenterTitle();                                                                                                                                                                                                       
66  h->GetYaxis()->CenterTitle();                                                                                                                                                                                                       
67  h->GetXaxis()->SetTitle("P.gtr.dp");                                                                                                                                                                                                
68  h->GetYaxis()->SetTitle(" Efficiency");                                                                                                                                                                                             
69  h->Draw("");                                                                                                                                                                                                                        
70  pEff->Draw("same");                                                                                                                                                                                                                 
71                                                                                                                                                                                                                                      
72  // c1->cd(2);                                                                                                                                                                                                                       
73  // h1[k]->Draw();                                                                                                                                                                                                                   
74                                                                                                                                                                                                                                      
75}                                                                                                                                                                                                                                     
                                                                        
